rpms:
  - clevis
  - clevis-dracut
  - clevis-udisks2
  - cockpit
  - freeipa-client
  - kodi
  - vim
  - vim-default-editor
  - zenity
flatpaks:
  - com.github.tchx84.Flatseal
  - com.mastermindzh.tidal-hifi
  - io.freetubeapp.FreeTube
  - io.github.TransmissionRemoteGtk
  - org.keepassxc.KeePassXC
  - org.videolan.VLC
